### ISSUE TITLE
Reformat issue confirmation output on using Multi Issue File

### ISSUE THREAD

**Issue by tohanss** [repobee/repobee-feedback#13]
Right now when opening issues repobee asks for confirmation on these and the way the text is formatted doesn't really do it for my eyes.
```
wagmode$ repobee issues feedback --mi issues.md -a task-15
Processing issue "Pass" for student1-task-15: Now this is c++!

dolor sit amet
Open issue "Pass" in repo student1-task-15? (y/n) y
Processing issue "Fail" for student2-task-15: 
Open issue "Fail" in repo student2-task-15? (y/n) y
Processing issue "Pass" for student3-task-15: more lorem ipsum, 

more dolor sit amet
Open issue "Pass" in repo student3-task-15? (y/n) 
````
I think this feels a bit cluttered, especially when each issue is given one by one it is sometimes difficult to directly see what is the new/old issue. Instead I would want something like this:

```
wagmode$ repobee issues feedback --mi issues.md -a task-15

Processing issue "Pass" for student1-task-15: 
    >Now this is c++!
    >
    >lorem ispum dolor sit amet
Open issue "Pass" in repo student1-task-15? (y/n) y

Processing issue "Fail" for student2-task-15: 
Open issue "Fail" in repo student2-task-15? (y/n) y

Processing issue "Pass" for student3-task-15: 
    >More Lorem isum
    >
    >More dolor sit amet
Open issue "Pass" in repo student3-task-15? (y/n) 
```

So the changes i can think of right now is:
* Separate each issue with empty line
* Indent issue text and/or place in some kind of block

This becomes even more usefull for larger issues. 

Alternatively, we can also make it so that when a new issue is shown in the terminal we make it so that while in "approval mode" only the current issue is shown. @slarse  what do you think?

**Comment by slarse** [comment]
I agree that it's not easy on the eyes.

> Indent issue text and/or place in some kind of block

This sounds like a reasonably easy-to-implement solution.

> Alternatively, we can also make it so that when a new issue is shown in the terminal we make it so that while in "approval mode" only the current issue is shown

This would also be neat. It's a little bit tricky to get it to look super nice, as you'd have to "erase" precisely what was printed. We do have reliance on ANSI escape codes, so the ANSI code for clearing the screen would also work (although it won't quite look as nice, and scrolling up afterwards may be a PITA). For that solution, printing this in between each "yes/no" would do the trick:

```python
import sys

sys.stdout.write("\033[2J\033[H")
```

`\033[2J` is the escape code for clearing the terminal, and `\033[H` is the escape code for moving the cursor to the top left corner (home position).

Ps. The reason I use `sys.stdout.write` instead of `print` is that the latter inserts a newline.

**Comment by slarse** [comment]
I'm very much swamped with stuff to do, so if this is gonna happen someone else needs to contribute it :)

**Comment by marceloFA** [comment]
Can I work on this one?

**Comment by slarse** [comment]
@marceloFA Sure, go ahead! This issue entails some amount of creative freedom, experiment with the formatting to find something that looks nice. It might even be cool to use something like [rich](https://github.com/willmcgugan/rich).

**Comment by slarse** [comment]
@marceloFA Oh, and feel free to ping me if you need any help :)

**Comment by marceloFA** [comment]
Sure, thanks! <3 Working on it right now haha

**Comment by marceloFA** [comment]
Sure, thanks! <3 Working on it right now haha
